apiVersion: v1
kind: Service
metadata:
  name: stt-service
  labels:
    app: stt-service
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: http
    protocol: TCP
    name: http-traffic
  selector:
    app: stt-service
